import React from 'react';
import { Link } from 'react-router-dom';

const TorusDetailPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/#figures" className="text-amber-600 font-semibold text-sm hover:text-amber-700 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m15 18-6-6 6-6"/></svg>
            Back to figures
          </Link>
          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Detail</span>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl md:text-4xl font-bold heading-font text-slate-900 mb-2">
          The Torus
        </h1>
        <p className="text-slate-500 text-lg mb-12">
          A surface of revolution generated by revolving a circle in three-dimensional space about an axis coplanar with the circle.
        </p>

        <div className="space-y-12">
          {/* Geometric Definition */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 md:p-8 shadow-sm">
            <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center text-sm font-bold">1</span>
              Geometric Definition
            </h2>
            <p className="text-slate-600 leading-relaxed mb-4">
              If the revolving circle has radius <strong>r</strong> and the distance from the center of the tube to the center of the torus is <strong>R</strong>, the surface is defined by:
            </p>
            <ul className="space-y-2 text-slate-600">
              <li><strong>Major Radius (R):</strong> Distance from the center of the hole to the center of the tube.</li>
              <li><strong>Minor Radius (r):</strong> Radius of the tube itself.</li>
            </ul>
          </section>

          {/* Mathematical Formulas */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 md:p-8 shadow-sm">
            <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center text-sm font-bold">2</span>
              Mathematical Formulas
            </h2>
            <ul className="space-y-4 text-slate-600">
              <li><strong>Surface Area (A):</strong> <span className="font-mono bg-slate-100 px-2 py-1 rounded">A = 4π²Rr</span></li>
              <li><strong>Volume (V):</strong> <span className="font-mono bg-slate-100 px-2 py-1 rounded">V = 2π²Rr²</span></li>
              <li><strong>Implicit Equation:</strong> <span className="font-mono bg-slate-100 px-2 py-1 rounded text-sm">(R − √(x² + y²))² + z² = r²</span></li>
            </ul>
          </section>

          {/* Topological Properties */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 md:p-8 shadow-sm">
            <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center text-sm font-bold">3</span>
              Topological Properties
            </h2>
            <ul className="space-y-3 text-slate-600">
              <li><strong>Genus (g):</strong> A single torus has a genus of 1, meaning it has exactly one &quot;hole.&quot;</li>
              <li><strong>Euler Characteristic (χ):</strong> For a torus, χ = 0. This is calculated via the formula χ = 2 − 2g.</li>
              <li><strong>Homeomorphism:</strong> In topology, a torus is considered equivalent to a coffee mug because both shapes have exactly one hole and can be theoretically deformed into one another without cutting or gluing.</li>
            </ul>
          </section>

          {/* Important Features */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 md:p-8 shadow-sm">
            <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center text-sm font-bold">4</span>
              Important Features
            </h2>
            <ul className="space-y-3 text-slate-600">
              <li><strong>Villarceau Circles:</strong> On any torus, there exist two specific planes that intersect the surface in two perfect circles, distinct from the standard horizontal or vertical cross-sections.</li>
              <li><strong>Toroidal Coordinates:</strong> A curvilinear orthogonal coordinate system often used in physics (specifically in plasma physics and tokamak reactors) to describe positions on the surface.</li>
            </ul>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-200">
          <Link to="/#figures" className="inline-flex items-center gap-2 text-amber-600 font-semibold hover:text-amber-700">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m15 18-6-6 6-6"/></svg>
            Back to figures
          </Link>
        </div>
      </main>
    </div>
  );
};

export default TorusDetailPage;
